# Generated by Django 6.0.2 on 2026-02-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="predicted_likes",
            field=models.IntegerField(default=0),
        ),
    ]
