# Generated by Django 6.0.2 on 2026-02-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_post_predicted_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="sentiment",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
